{
    "name": "Myanmar NRC Format",
    "version": "16.0.1.0.0",
    "summary": "Myanmar NRC Format Management",
    "description": "Manage Myanmar National Registration Card (NRC) format with prefix and township codes",
    "category": "Sales",
    "author": "ZbyE Solution",
    "maintainer": "Rowan Ember",
    "website": "zbye.odoo.com",
    "support": "zbye.info@gmail.com",
    "images": ["static/description/banner.png"],
    "license": "LGPL-3",
    "depends": ["base","contacts"],
    "data": [
        "security/ir.model.access.csv",
        "data/nrc_prefix_data.xml",
        "data/nrc_township_code_data.xml",
        "data/nrc_type_data.xml",
        "views/nrc_prefix_views.xml",
        "views/nrc_township_code_views.xml",
        "views/nrc_type_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
